import type { DbPool } from '../db/pglite-store.js';
import { introspectSchema } from '../plugins/introspection/inspector.js';

export async function generateSchemaMd(db: DbPool, schemaName = 'public'): Promise<string> {
  const tableMap = await introspectSchema(db, schemaName);

  if (tableMap.size === 0) {
    return `# Vibebase Schema\n\nNo tables found in schema \`${schemaName}\`. Create tables via the Studio or by running migrations.\n`;
  }

  const lines: string[] = [
    '# Vibebase Schema',
    '',
    '> Auto-generated by Vibebase. Run `vibebase schema refresh` to update.',
    '',
    '## Tables',
    '',
  ];

  for (const [tableName, table] of tableMap) {
    lines.push(`### ${tableName}`);
    lines.push('');

    // Build a lookup from column name → foreign key info
    const fkMap = new Map(table.foreignKeys.map(fk => [fk.columnName, fk]));

    for (const col of table.columns) {
      const parts: string[] = [`\`${col.name}\` (${col.dataType}`];
      if (col.isPrimaryKey) parts.push(', primary key');
      if (!col.isNullable) parts.push(', required');
      if (col.columnDefault) parts.push(`, default ${col.columnDefault}`);
      const fk = fkMap.get(col.name);
      if (fk) parts.push(`, references ${fk.foreignTable}.${fk.foreignColumn}`);
      parts.push(')');
      lines.push(`- ${parts.join('')}`);
    }

    lines.push('');
  }

  lines.push('## Auth');
  lines.push('');
  lines.push('Users managed by Vibebase auth:');
  lines.push('```ts');
  lines.push(`await supabase.auth.signUp({ email: 'user@example.com', password: 'password' })`);
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}
